### ISSUE TITLE
500 Error when accessing the dashboard

### ISSUE THREAD

**Issue by unoriginalscreenname** [SciPhi-AI/R2R-Application#1]
I cloned the repo, updated nodejs, and installed pnpm.  I launched the r2r server in another terminal and ingested the documents.  After following the building instructions, i ran the final "pnpm build && pnpm start".  It runs the server on port 3000, but all i get is a /error/ 500 error when I try to access it.

**Comment by NolanTrem** [comment]
Hey @unoriginalscreenname thanks for flagging this! I made quite a few changes in #2 which should fix this. Let me know if it doesn't work for you now!

**Comment by NolanTrem** [comment]
Closing this out, but feel free to reopen if this issue isn't resolved. Thanks!
