### ISSUE TITLE
Error: Failed to collect page data for /collection/[collection_id]

### ISSUE THREAD

**Issue by MyraBaba** [SciPhi-AI/R2R-Application#102]
Hi, 

cloned latest r2r-application 

pnpm install
pnpm build  gives below error:

> r2r-dashboard@1.0.0 build /home/bc/Projects/ODS/R2R-Application_v25Sept
> next build

  ▲ Next.js 14.2.5

 ✓ Linting and checking validity of types
   Creating an optimized production build ...
 ✓ Compiled successfully
   Collecting page data  ..TypeError: Promise.withResolvers is not a function
    at file:///home/bc/Projects/ODS/R2R-Application_v25Sept/node_modules/.pnpm/pdfjs-dist@4.4.168/node_modules/pdfjs-dist/build/pdf.mjs:5448:35
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:432:15)

> Build error occurred
Error: Failed to collect page data for /collection/[collection_id]
    at /home/bc/Projects/ODS/R2R-Application_v25Sept/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.78.0/node_modules/next/dist/build/utils.js:1268:15 {
  type: 'Error'
}
   Collecting page data  . ELIFECYCLE  Command failed with exit code 1.

**Comment by NolanTrem** [comment]
Thanks, @MyraBaba. The latest build is running so you shouldn't see this anymore!
