### ISSUE TITLE
create new user in Dashboard

### ISSUE THREAD

**Issue by MyraBaba** [SciPhi-AI/R2R-Application#105]
How to create new user in dashboard ? cant find ?

**Comment by NolanTrem** [comment]
To do this in the dashboard, you can do so with the "Sign up with Email" flow. We hope to expose a way to do this as a superuser in the near future, as well.

![Screenshot 2024-10-01 at 4 54 56 PM](https://github.com/user-attachments/assets/acd7baff-23c0-41d2-b475-6e68729fdaa6)
![Screenshot 2024-10-01 at 4 55 15 PM](https://github.com/user-attachments/assets/fe428017-d1ab-4daf-8b24-6074df96140b)


And then from the Admin view:
![Screenshot 2024-10-01 at 4 55 38 PM](https://github.com/user-attachments/assets/aafa1c1f-1d42-4760-ae80-9af7db9236d2)
![Screenshot 2024-10-01 at 4 56 22 PM](https://github.com/user-attachments/assets/ada1928c-4f23-4aae-8718-aadd7a557057)
