### ISSUE TITLE
Can't list all the documents. The console shows Error: Minified React error #418

### ISSUE THREAD

**Issue by yaohuiwu** [SciPhi-AI/R2R-Application#65]
**Describe the bug**
The document is loading forever. 

**To Reproduce**

1. Go to 'http://localhost'
2. Click on 'Documents'
3. Scroll down to 'Nothing'

**Expected behavior**
All the documents are listed

**Screenshots**
![image](https://github.com/user-attachments/assets/be825c50-3c58-4804-ba9f-dcdb394e6c4d)

**Desktop (please complete the following information):**

- OS: Mac OS Big Sur 11.7.8
- Browser chrome 126.0.6478.183
- Version 1.0.0

**Smartphone (please complete the following information):**
None

**Additional context**
Before this error happens, I uploaded a file which name contains blank chars - "PostgreSQL High Availability Cookbook ( PDFDrive )".

**Comment by NolanTrem** [comment]
Hey @yaohuiwu can you confirm how you uploaded this? Was it through the R2R cli? The dashboard?

**Comment by yaohuiwu** [comment]
I uploaded through the r2r-js library.

**Comment by NolanTrem** [comment]
Hey @yaohuiwu this should be solved by #69. It looks like in some browser environments there were issues with auth that were causing hydration issues. Feel free to reopen if this doesn't solve it!
