### ISSUE TITLE
Error: Error in input stream

### ISSUE THREAD

**Issue by linuxreitt** [SciPhi-AI/R2R-Application#74]
**Describe the bug**
When using Question and Answer

**To Reproduce**

1. Go to question and answer, enter question into text input
2. Click on Send (Blue Arrow)
3. Error appears on screen "Error: Error in input stream"

**Expected behavior**
Answer to question

**Screenshots**
![error](https://github.com/user-attachments/assets/da85de8e-ca04-4923-bc55-32ec64c0c5fa)

**Desktop (please complete the following information):**

- OS: Linux (Debian)
- Browser Firefox
- Version
129.0 Firefox Release

**Additional context**
RAG Agent working as expected.

**Comment by linuxreitt** [comment]
Hi @NolanTrem. Here is my config, admittedly I became a little confused trying to set everything up, also I couldn't get the docker container to connect to my local ollama and so I used the following comand r2r --config-name=local_llm serve r2r --config-name=local_llm serve --exclude-ollama=False --docker. Should I still set an API Key set? Thank you.

<h4 class="text-xl font-bold text-white pb-2">Config</h4><div class="overflow-x-auto">
Key | Value
-- | --
crypto |  
provider | "bcrypt"
extra_fields |  
auth |  
provider | "r2r"
require_authentication | false
require_email_verification | false
access_token_lifetime_in_minutes | 60
refresh_token_lifetime_in_days | 7
default_admin_email | "admin@example.com"
default_admin_password | "change_me_immediately"
extra_fields |  
embedding |  
provider | "ollama"
base_model | "mxbai-embed-large"
base_dimension | 1024
batch_size | 32
add_title_as_prefix | true
concurrent_request_limit | 32
max_retries | 2
initial_backoff | 1
max_backoff | 60
extra_fields |  
kg |  
batch_size | 1
kg_extraction_prompt | "few_shot_ner_kg_extraction"
kg_search_prompt | "kg_search"
extra_fields |  
parsing |  
provider | "r2r"
excluded_parsers | ["gif", "jpeg", "jpg", "png", "svg", "mp3", "mp4"]
override_parsers | []
extra_fields |  
chunking |  
provider | "r2r"
method | "recursive"
chunk_size | 512
chunk_overlap | 50
extra_fields |  
completion |  
provider | "litellm"
concurrency_limit | 16
max_retries | 2
initial_backoff | 1
max_backoff | 60
extra_fields |  
concurrent_request_limit | 1
generation_config |  
model | "ollama/llama3.1"
temperature | 0.1
top_p | 1
max_tokens_to_sample | 1024
stream | false
add_generation_kwargs |  
logging |  
provider | "local"
log_table | "logs"
log_info_table | "log_info"
extra_fields |  
prompt |  
provider | "r2r"
default_system_name | "default_system"
default_task_name | "default_rag"
extra_fields |  
database |  
provider | "postgres"
extra_fields |  
agent |  
system_instruction_name | "rag_agent"
tool_names | ["search"]
stream | true
generation_config |  
model | "ollama/llama3.1"
temperature | 0.1
top_p | 1
max_tokens_to_sample | 1024
stream | false
add_generation_kwargs |  
eval |  
extra_fields |  

</div>

**Comment by NolanTrem** [comment]
Hey @linuxreitt we've done quite a bit of updating between R2R, the js sdk, and the application. Should be fixed now!
