### ISSUE TITLE
 ENOENT  ENOENT: no such file or directory, open 'D:\Users\nolantremelling\R2R\js\sdk\r2r-js-0.3.3.tgz'

### ISSUE THREAD

**Issue by dev3py** [SciPhi-AI/R2R-Application#98]
**Describe the bug**
I followed the installation process in the readme file.

**To Reproduce**
I cloned this repo moved to this directory and ran pnpm install. I got this error

D:\Mydir\R2R-Application>pnpm i
 ENOENT  ENOENT: no such file or directory, open 'D:\Users\nolantremelling\R2R\js\sdk\r2r-js-0.3.3.tgz'

**Comment by NolanTrem** [comment]
Hey @dev3py you should likely build off of the Docker image we serve with R2R, as we're moving away from having a locally served version of this as the recommended install. This will get you the most recent supported build.

https://github.com/SciPhi-AI/R2R

You can do this by running `r2r serve --docker`

**Comment by dev3py** [comment]
@NolanTrem  Thank i installed the docker version with openai key.
In chats There are two options in dropdows RAG agent , Question and answer. In the RAG agent i am asking questions its returning the answer to the question in general. (But not from the document that i have uploaded).  But when i select the Question and answer in the drop down and i asked the prompt. it got error.
In docker logs i go this error
2024-09-20 12:18:08     | litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=
2024-09-20 12:18:08     |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by NolanTrem** [comment]
Looking into this, thanks!
